### ISSUE TITLE
NullReferenceException in ServiceControlInstaller.GetManagementPath

### ISSUE THREAD

**Issue by SimonCropp** [Particular/PlatformInstaller#182] opened 2016-05-12 23:53 UTC
Error logged in raygun

```
Message: NullReferenceException: Object reference not set to an instance of an object.
ServiceControlInstaller.GetManagementPath():55
ServiceControlInstaller.b__16_0():0
SimpleCommand.Execute(Object parameter):0
MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated):74
System.Windows.Controls.Primitives.ButtonBase.OnClick():19
System.Windows.Controls.Button.OnClick():26
System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e):68
System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e):29
System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget):0
```

**Comment by SimonCropp** [comment] 2016-05-12 23:55
so clearly the line number is wrong

**Comment by SimonCropp** [comment] 2016-05-13 00:01
@gbiellem thoughts on which of those registry api calls could return null?

**Comment by robvanuden** [comment] 2016-05-19 19:29
I've got the same problem during installation. Is there any workaround?

Mine also crashes at the GetManagementPath method:
2016-05-19 21:16:58.066 +02:00 [Error] ExceptionHandler Dispatcher.CurrentDispatcher.UnhandledException
System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceControlInstaller.GetManagementPath()
   at ServiceControlInstaller.<GetAfterInstallActions>b__16_0()
   at SimpleCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
......

**Comment by robvanuden** [comment] 2016-05-19 19:46
I reproduces the issue for me locally in a console app.
The problem is in this part
```
var key32 = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey(name);
            return (string)key32.GetValue("ManagementApp");
```
key32 is null on my machine, so calling the GetValue method on it throws an exception.

This is all I can give you I guess... Hope it helps!
If you need more information, just ask :-)
This is all I can give you I guess... Hope it helps!

**Comment by SimonCropp** [comment] 2016-05-19 20:30
@robvanuden that is really helpful. We will do some more research and get back to u

**Comment by gbiellem** [comment] 2016-05-31 08:51
@robvanuden 

I was hoping you could give me a little more info on this:

1. Did the ServiceControl Management installation succeed through the Platfom installer? That install should have created a reg entry for ManagementApp in one of the two locations.

2.  Is it possible to get the logs for the SC management installation? It should be located in the folder `%Temp%\Particular\PlatformInstaller`

**Comment by gbiellem** [comment] 2016-07-26 06:04
Waiting on feedback or an new raygun report with the more detailed logging before we can proceed

**Comment by gbiellem** [comment] 2016-10-25 03:36
No more instances of this have occured so closing

**Closed by gbiellem** 2016-10-25 03:36 UTC
Labels: Tag: Blocked, Type: Bug
